import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Disclaimer | Prompts & Tools",
  description: "Important disclaimers about the content on Prompts & Tools.",
};
export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-5 sm:px-8 py-20">
      <p className="text-xs mb-4" style={{ color: "#4A5580" }}>Last updated: June 2026</p>
      <h1 className="text-3xl md:text-4xl font-bold mb-4 text-gradient" style={{ fontFamily: "var(--font-space-grotesk)", letterSpacing: "-0.025em" }}>Disclaimer</h1>
      <p className="mb-10 text-sm" style={{ color: "#6B7DB8" }}>Please read this disclaimer carefully before using promptsandtools.online.</p>

      {[
        { h: "General Information Only", body: "All content on Prompts & Tools is provided for general informational and educational purposes only. Nothing on this site constitutes professional advice of any kind. We are not software engineers, licensed consultants, or certified AI specialists. All opinions expressed are our own based on personal experience and testing." },
        { h: "No Guarantee of Results", body: "The tools, workflows, and strategies discussed on this site have worked for us and many readers, but results may vary. We make no guarantee that any AI tool, automation workflow, or productivity technique will produce the same results for you. Success depends on many individual factors including skill level, effort, specific use case, and the tool's current capabilities." },
        { h: "Third-Party Tools and Pricing", body: "We review and discuss third-party AI tools and software. Prices, features, and availability change frequently and without notice. Always verify current pricing and features directly with the vendor before making a purchase decision. We are not responsible for any changes made by third parties to their products or pricing after our review is published." },
        { h: "AI Tool Accuracy", body: "AI tools can produce inaccurate, incomplete, or misleading outputs. Content generated by AI tools should always be reviewed and verified by a human before being published, shared, or acted upon in any professional context. We are not responsible for decisions made based on AI-generated content." },
        { h: "Affiliate Links", body: "This site contains affiliate links. See our Affiliate Disclosure page for full details. The presence of an affiliate link does not constitute an endorsement beyond what is stated in our review." },
        { h: "External Links", body: "We may link to external websites for reference. We do not control the content of external sites and are not responsible for their accuracy, legality, or privacy practices. Links to external sites do not constitute endorsement." },
        { h: "Limitation of Liability", body: "To the fullest extent permitted by law, Prompts & Tools shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your use of this website or the information contained within it." },
      ].map(({ h, body }) => (
        <div key={h} className="mb-8">
          <h2 className="text-lg font-bold mb-3" style={{ color: "#CBD5E1", fontFamily: "var(--font-space-grotesk)" }}>{h}</h2>
          <p className="text-sm leading-relaxed" style={{ color: "#6B7DB8" }}>{body}</p>
        </div>
      ))}
    </div>
  );
}
